name: "pr-title-editor-action"
description: "append or prepend text to the title of your PRs"
author: "adaminglehart"

# Define your inputs here.
inputs:
  token:
    description: "Your github token"
    required: true
  titleText:
    description: "the text to add to your PR titles"
    required: true
  placement:
    description: "where to add the text (prefix or suffix)"
    required: true
    default: "prefix"

outputs:
  time:
    description: "Your output description here"

runs:
  using: node18
  main: dist/index.js
